name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into Server and Pull Latest Code
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          cd ../../hobohippie
          git pull origin main
        EOF

    - name: Install Server Dependencies
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          cd /path/to/your/app
          npm install
        EOF

    - name: Install Client Dependencies
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          cd /path/to/your/app/client  # Change this if your client directory is different
          npm install
        EOF

    - name: Build Client
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          cd /path/to/your/app/client  # Adjust this if necessary
          npm run build
        EOF

    - name: Replace Old Build
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          # Adjust the paths below according to your setup
          rm -rf /path/to/old/build/*  # Clear the old build
          cp -R /path/to/your/app/client/build/* /path/to/old/build/  # Copy the new build
        EOF

    - name: Restart Nginx
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          sudo systemctl restart nginx
        EOF

    - name: Restart PM2
      run: |
        ssh deployer@66.179.241.155 << 'EOF'
          pm2 restart all  # You can specify your app name if needed
        EOF
