name: Build and Deploy

on:
  push:
    branches:
      - main  # Triggers the workflow on any push to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run the build script
      - name: Run build
        run: npm run build

      # Add SSH key to the agent for deployment
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Deploy via SSH
      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@66.179.189.159 'cd /hobohippie && git pull origin main && npm install && npm run build && pm2 restart hobohippie'
