name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add SSH Key to Known Hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 66.179.241.155 >> ~/.ssh/known_hosts

    - name: SSH into Server and Pull Latest Code
      run: |
        ssh deployer@66.179.241.155 'cd ../../hobohippie && git pull'

    - name: Install Server Dependencies
      run: |
        ssh deployer@66.179.241.155 'cd ../../hobohippie/server && npm install'

    - name: Install Client Dependencies
      run: |
        ssh deployer@66.179.241.155 'cd ../../hobohippie/client && npm install'

    - name: Build Client
      run: |
        ssh deployer@66.179.241.155 'cd ../../hobohippie/client && npm run build'

    - name: Restart PM2
      run: |
        ssh deployer@66.179.241.155 '/home/deployer/.nvm/versions/node/v20.18.0/bin/pm2 restart all'

    - name: Restart Nginx
      run: |
        ssh deployer@66.179.241.155 'sudo systemctl restart nginx'
